# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_density_1iter <- function(grid, weights, means, variances) {
    .Call(`_thinnedDDP_compute_density_1iter`, grid, weights, means, variances)
}

compute_density <- function(grid, weights, means, variances) {
    .Call(`_thinnedDDP_compute_density`, grid, weights, means, variances)
}

compute_density_1iter1DP <- function(grid, weights, means, variances) {
    .Call(`_thinnedDDP_compute_density_1iter1DP`, grid, weights, means, variances)
}

compute_density_1DP <- function(grid, weights, means, variances) {
    .Call(`_thinnedDDP_compute_density_1DP`, grid, weights, means, variances)
}

sampler_DP_arma <- function(nrep, burnin, thinning_factor, y, trunc, mu0, tau0, gamma0, lambda0, alpha, mu_start, sigma2_start, cl_start, progressbar) {
    .Call(`_thinnedDDP_sampler_DP_arma`, nrep, burnin, thinning_factor, y, trunc, mu0, tau0, gamma0, lambda0, alpha, mu_start, sigma2_start, cl_start, progressbar)
}

sampler_thinnedDDP_arma <- function(nrep, burnin, thinning_factor, y, group, trunc, mu0, tau0, gamma0, lambda0, alpha, a_beta, b_beta, mu_start, sigma2_start, cl_start, progressbar) {
    .Call(`_thinnedDDP_sampler_thinnedDDP_arma`, nrep, burnin, thinning_factor, y, group, trunc, mu0, tau0, gamma0, lambda0, alpha, a_beta, b_beta, mu_start, sigma2_start, cl_start, progressbar)
}

