// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_density_1iter
arma::mat compute_density_1iter(arma::vec grid, arma::mat weights, arma::vec means, arma::vec variances);
RcppExport SEXP _thinnedDDP_compute_density_1iter(SEXP gridSEXP, SEXP weightsSEXP, SEXP meansSEXP, SEXP variancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type means(meansSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type variances(variancesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_density_1iter(grid, weights, means, variances));
    return rcpp_result_gen;
END_RCPP
}
// compute_density
Rcpp::List compute_density(arma::vec grid, arma::cube weights, arma::mat means, arma::mat variances);
RcppExport SEXP _thinnedDDP_compute_density(SEXP gridSEXP, SEXP weightsSEXP, SEXP meansSEXP, SEXP variancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type means(meansSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type variances(variancesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_density(grid, weights, means, variances));
    return rcpp_result_gen;
END_RCPP
}
// compute_density_1iter1DP
arma::mat compute_density_1iter1DP(arma::vec grid, arma::vec weights, arma::vec means, arma::vec variances);
RcppExport SEXP _thinnedDDP_compute_density_1iter1DP(SEXP gridSEXP, SEXP weightsSEXP, SEXP meansSEXP, SEXP variancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type means(meansSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type variances(variancesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_density_1iter1DP(grid, weights, means, variances));
    return rcpp_result_gen;
END_RCPP
}
// compute_density_1DP
Rcpp::List compute_density_1DP(arma::vec grid, arma::mat weights, arma::mat means, arma::mat variances);
RcppExport SEXP _thinnedDDP_compute_density_1DP(SEXP gridSEXP, SEXP weightsSEXP, SEXP meansSEXP, SEXP variancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type means(meansSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type variances(variancesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_density_1DP(grid, weights, means, variances));
    return rcpp_result_gen;
END_RCPP
}
// sampler_DP_arma
Rcpp::List sampler_DP_arma(int nrep, int burnin, const arma::vec& y, int trunc, double mu0, double tau0, double gamma0, double lambda0, double alpha, arma::vec mu_start, arma::vec sigma2_start, arma::vec cl_start, bool progressbar);
RcppExport SEXP _thinnedDDP_sampler_DP_arma(SEXP nrepSEXP, SEXP burninSEXP, SEXP ySEXP, SEXP truncSEXP, SEXP mu0SEXP, SEXP tau0SEXP, SEXP gamma0SEXP, SEXP lambda0SEXP, SEXP alphaSEXP, SEXP mu_startSEXP, SEXP sigma2_startSEXP, SEXP cl_startSEXP, SEXP progressbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type trunc(truncSEXP);
    Rcpp::traits::input_parameter< double >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< double >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< double >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_start(mu_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2_start(sigma2_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl_start(cl_startSEXP);
    Rcpp::traits::input_parameter< bool >::type progressbar(progressbarSEXP);
    rcpp_result_gen = Rcpp::wrap(sampler_DP_arma(nrep, burnin, y, trunc, mu0, tau0, gamma0, lambda0, alpha, mu_start, sigma2_start, cl_start, progressbar));
    return rcpp_result_gen;
END_RCPP
}
// sampler_thinnedDDP_arma
Rcpp::List sampler_thinnedDDP_arma(int nrep, int burnin, const arma::vec& y, const arma::vec& group, int trunc, double mu0, double tau0, double gamma0, double lambda0, double alpha, double a_beta, double b_beta, arma::vec mu_start, arma::vec sigma2_start, arma::vec cl_start, bool progressbar);
RcppExport SEXP _thinnedDDP_sampler_thinnedDDP_arma(SEXP nrepSEXP, SEXP burninSEXP, SEXP ySEXP, SEXP groupSEXP, SEXP truncSEXP, SEXP mu0SEXP, SEXP tau0SEXP, SEXP gamma0SEXP, SEXP lambda0SEXP, SEXP alphaSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP mu_startSEXP, SEXP sigma2_startSEXP, SEXP cl_startSEXP, SEXP progressbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type trunc(truncSEXP);
    Rcpp::traits::input_parameter< double >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< double >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< double >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< double >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_start(mu_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2_start(sigma2_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cl_start(cl_startSEXP);
    Rcpp::traits::input_parameter< bool >::type progressbar(progressbarSEXP);
    rcpp_result_gen = Rcpp::wrap(sampler_thinnedDDP_arma(nrep, burnin, y, group, trunc, mu0, tau0, gamma0, lambda0, alpha, a_beta, b_beta, mu_start, sigma2_start, cl_start, progressbar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thinnedDDP_compute_density_1iter", (DL_FUNC) &_thinnedDDP_compute_density_1iter, 4},
    {"_thinnedDDP_compute_density", (DL_FUNC) &_thinnedDDP_compute_density, 4},
    {"_thinnedDDP_compute_density_1iter1DP", (DL_FUNC) &_thinnedDDP_compute_density_1iter1DP, 4},
    {"_thinnedDDP_compute_density_1DP", (DL_FUNC) &_thinnedDDP_compute_density_1DP, 4},
    {"_thinnedDDP_sampler_DP_arma", (DL_FUNC) &_thinnedDDP_sampler_DP_arma, 13},
    {"_thinnedDDP_sampler_thinnedDDP_arma", (DL_FUNC) &_thinnedDDP_sampler_thinnedDDP_arma, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_thinnedDDP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
